version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '10082:8080'
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - siRelawan/.env
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
  db:
    image: postgres:14-alpine
    ports:
      - '15082:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - backend-network


volumes:
  db:
    driver: local

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
