version: '3.8'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=propensiA10
      - POSTGRES_PASSWORD=salamsetara
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local